removed lines from Makefile, added prerm script, extended cleanup method

diff --git a/egpu-switcher b/egpu-switcher
--- a/egpu-switcher
+++ b/egpu-switcher
@@ -22,6 +22,8 @@ XFILE_BACKUP=$XFILE.backup
 TMP_DIR=/tmp/egpu-switcher
 TMP_FILE=$TMP_DIR/results
 TMP_TEMPLATE=/usr/share/egpu-switcher/xorg.conf.template
+INITD_SCRIPT=/etc/init.d/egpu-switcher
+INITD_RC5_SYMLINK=/etc/rc5.d/S15egpu-switcher
 DATETIME=$(date '+%Y%m%d%H%M%S')
 NUMBER_REGEX='^[0-9]+$'
 
@@ -172,6 +174,16 @@ setup() {
 	# Executing the switch command to create the xorg.conf file
 	switch auto $1
 
+	# setup startup script
+	touch $INITD_SCRIPT
+	chmod +x $INITD_SCRIPT
+	echo "egpu-switcher switch auto" > $INITD_SCRIPT
+	ln -sf $INITD_SCRIPT $INITD_RC5_SYMLINK
+
+	if ! [ -f $INITD_SCRIPT ]; then
+		echo -e "$ERROR Could not create the init.d startup script."
+	fi
+
 	echo -e "$SUCCESS Done... Setup finished"
 }
 
@@ -229,6 +241,8 @@ cleanup() {
 	rm -rfd $TMP_DIR
 	rm -rf $XFILE_EGPU
 	rm -rf $XFILE_INTERNAL
+	rm -rf $INITD_RC5_SYMLINK
+	rm -rf $INITD_SCRIPT
 
 	# delete the xorg.conf file, if it is a symlink and restore the last backup
 	if [ -L $XFILE ]; then
@@ -254,3 +268,5 @@ fi
 if [ $1 = "cleanup" ]; then
 	cleanup
 fi
+
+# systemctl restart display-manager.service
